---
name: nox

"on":
  workflow_call:

jobs:
  nox:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - session: spelling
            python-versions: "3.12"
          - session: formatters_check
            python-versions: "3.12"
          - session: build
            python-versions: "3.12"
    name: "Run nox ${{ matrix.session }} session"
    steps:
      - name: Check out repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - name: Setup nox
        uses: wntrblm/nox@3284968a16fa5bd7fc0cc64a69a531404ccb4756 # 2026.07.11
        with:
          python-versions: "${{ matrix.python-versions }}"
      - name: "Run nox -s ${{ matrix.session }}"
        run: |
          nox -s "${{ matrix.session }}"

  commitlint:
    runs-on: ubuntu-latest
    name: "Run nox commitlint session"
    steps:
      - name: Check out PR head
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0
          persist-credentials: false
      - name: Fetch main branch
        run: git fetch origin main
      - name: Setup nox
        uses: wntrblm/nox@3284968a16fa5bd7fc0cc64a69a531404ccb4756 # 2026.07.11
        with:
          python-versions: "3.12"
      - name: Run nox commitlint session
        run: |
          nox -s commitlint -- origin/main..HEAD
